source 'https://github.com/CocoaPods/Specs.git'

target 'UINavigationControllerGameFade', :exclusive => true do
  pod "UINavigationControllerGameFade", :path => "../"
end

target 'Tests', :exclusive => true do
  pod "UINavigationControllerGameFade", :path => "../"

  
end
